### ISSUE TITLE
content of crl-cron.sh

### ISSUE THREAD

**Issue by flapouille** [kyl191/ansible-role-openvpn#109]
Hello, 

I am curious about how crl-cron.sh is supposed to work. 

Here is the content of the file 

```
#!/bin/sh 
lastUpdate=$(date --date "$(openssl crl -in /etc/openvpn/keys/ca-crl.pem -noout -lastupdate | cut -d'=' -f2)" +%s) 
nextUpdate=$(date --date "$(openssl crl -in /etc/openvpn/keys/ca-crl.pem -noout -nextupdate | cut -d'=' -f2)" +%s) 
if [ $(( (nextUpdate - lastUpdate) / 86400 )) -le 10 ]; then 
    sh /etc/openvpn/keys/revoke.sh  &nbsp;
fi
```

lastupdate and nextupdate are static values ; they are both not changing unless explicitely modified (see 
 https://community.openvpn.net/openvpn/wiki/CertificateRevocationListExpired ). 

that's why I am not understanding the if statement. It will systematically be 30 (days) ? 

Can someone explain? 

Today I had to manually launch the script /etc/openvpn/keys/revoke.sh because there nextUpdate < now. 

Thanks

**Comment by Furragen** [comment]
Would it not be easier to just call the revoke.sh every month on maybe the 26th day?

Also, I'm not sure how active the author of this role still is.

**Comment by kyl191** [comment]
My understanding is it should be regenerating the CRL periodically. I'm not sure what the period between regeneration is though. Maybe having a fixed day of the month is good enough.

I personally disable the CRL because my use of this role is tied to the lifetime of VMs, and it's all personal use so I haven't needed to disable any certs.
