### ISSUE TITLE
remove the user

### ISSUE THREAD

**Issue by arbabnazar** [kyl191/ansible-role-openvpn#35]
@kyl191 what if I want to remove the user, I didn't find anything related to it over the net.  Do you have an idea about it. Thanks

**Comment by kyl191** [comment]
Remove the user?

As in remove the `openvpn` user from the server, or deauthorize a generated certificate?

**Comment by arbabnazar** [comment]
Deauthorize the already generated certificate

**Comment by kyl191** [comment]
I took a closer look at this - it's technically possible to revoke a generated cert, but I don't have support for it in the playbook right now. 

I don't have enough bandwidth to allow me to get to adding such support right now either, so this will have to go on the backlog.

**Comment by arbabnazar** [comment]
Can you please give me the rough idea, I'll take it from there and
contribute in this repo. Thanks,

**Comment by Logan2211** [comment]
I started to write a PR against this role for this specific issue but instead decided to write a separate role to also implement a different approach for OpenVPN configuration which I think offers more flexibility. FWIW, the specific cert revocation work in this issue is mostly encapsulated in https://github.com/Logan2211/ansible-openvpn/commit/6996249089dc82142f63c541934d9e5aa2db2c00 and could probably be adapted to work in this role without too much difficulty.

Instead of using `openssl x509` to sign certificates, you build an openssl CA repository and use the `openssl ca` tool to manage the repo (sign certs, revoke certs, etc.)

**Comment by kyl191** [comment]
This is stale, I'm closing it to clean up this repo.

Reopen it if you want, thanks.
