### ISSUE TITLE
Could not find the requested service iptables: cannot enable

### ISSUE THREAD

**Issue by A-Gordon** [kyl191/ansible-role-openvpn#36]
The install fails with the following error 
`{"changed": false, "failed": true, "msg": "Could not find the requested service iptables: cannot enable"}`

Ansible version: 2.2.2.0 tested on 2.2.1.0 also
OS: Mac OSX 
External Host: Centos 7 AWS AMI ami-7abd0209

**Comment by kyl191** [comment]
The CentOS AMIs on AWS are [https://github.com/kyl191/ansible-role-openvpn/issues/26#issuecomment-281002483](questionable) - they're stripped down to the absolute bare minimum, iptables isn't installed.

I'm not confident in adding a blanket 'install `iptables`' rule, I would suggest that you either add an install `pre_task` to the playbook which is running the role (see my sample playbook on https://github.com/kyl191/ansible-role-openvpn/issues/26#issuecomment-281001576), or otherwise manually install iptables before running the playbook.

**Comment by A-Gordon** [comment]
Thanks for the update, I managed to find that as well. I was going to submit a PR but it looks like you're not keen on that so I'll use the pre_task to my playbook. 

I'm getting an issue using the generated OVPN file with Viscosity, I suspect it's a Mac OS issue though.
