### ISSUE TITLE
VERIFY ERROR: depth=0, error=CRL has expired: CN=xxxxxxxxxx

### ISSUE THREAD

**Issue by mikegleasonjr** [kyl191/ansible-role-openvpn#54]
Hi, I just got this error on Raspbian Stretch (raspberry pi) when connecting to my server.

Was connecting fine until today (been using it for 2-3 months now)

How can I fix this problem, tried running the role again to no avail

Thanks !

**Comment by rdeknijf** [comment]
Cert verification fails if the CRL has expired, but because of a bug there's no way to disable this verification. https://github.com/kyl191/ansible-role-openvpn/pull/59 should fix it definitively, in the meantime you could try removing and re-adding a user. That should force the CRL to be regenerated and be valid for another month.

Perhaps this regeneration should be done on a timer to be more secure, but at least you should be able to turn the check off.

**Comment by mikegleasonjr** [comment]
Thanks that's what I did in the end, re-created the user. Sorry for not getting back to you after I resolved it 🙄

**Comment by rdeknijf** [comment]
No problem, glad you got it working.
